### ISSUE TITLE
Simple "try out" template

### ISSUE THREAD

**Issue by FH-Inway** [fscpscollaborative/fscps#67]
I think the current templates and onboarding documentation work. For people unfamiliar with FSC-PS and GitHub, I propose a more simplified template and onboarding.

The template would just be for D365FSC extensions. It would have one build action and just the minimum of .json files to support that. Documentation for the template would explain 
- how to set it up 
- how to connect to it from a development environment
- how to add a simple extension
- how to run the build for that extension

Future work could add similar templates for commerce extensions. It could also add documentation that show how to add the other stuff (CI, CD, repo update, ...).

Aside from a more simplified onboarding, I also think this would remove concerns around allowing a third party access to the repo (the repo update) or having to upload an existing extension to a public url (for the import).

**Comment by onikolaiev** [comment]
Good idea. Will create a super simple guide.

**Comment by FH-Inway** [comment]
I gave this a shot with https://github.com/FH-Inway/fscps.fscsimpletpl
Tested it with https://github.com/FH-Inway/fscsimpletpltest01
